# Use an official Node.js runtime as a parent image
FROM node:18

# Set the working directory in the container
WORKDIR /home

# Copy the package.json and package-lock.json (if available)
COPY . /home

# Install application dependencies
RUN npm install

# Copy the application code into the container
COPY . .

# Expose the port the app runs on
EXPOSE 5011

# Define the command to run the application
CMD ["node", "gm.js"]
